# Generated by Django 4.1.2 on 2022-11-03 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0004_alter_article_likes_like"),
    ]

    operations = [
        migrations.RenameField(
            model_name="like",
            old_name="post",
            new_name="article",
        ),
    ]
