# Generated by Django 4.1.2 on 2022-11-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myblog", "0006_alter_comment_options_rename_content_comment_body_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
            ],
        ),
    ]
